import os
TELEGRAM_BOT_TOKEN = os.getenv('TELEGRAM_BOT_TOKEN', '7111532274:AAFq9LvV1t_n_buNDHp_cWCScl9KXW8mhNM')
TELEGRAM_CHAT_ID = os.getenv('TELEGRAM_CHAT_ID', '6737175223')
CHECK_INTERVAL_MINUTES = int(os.getenv('CHECK_INTERVAL_MINUTES', 60))
PORT = int(os.getenv('PORT', 10000))
DEFAULT_COINS = ['BTC', 'ETH', 'BNB', 'SOL', 'XRP']
